version: "3.9"
services:
  wireguard-mullvad-usa:
    image: ghcr.io/linuxserver/wireguard
    container_name: wireguard-mullvad-usa
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1420
      - PGID=1420
      - TZ=America/New_York
    volumes:
      - /services/mullvad-usa/wireguard:/config:Z
      - /lib/modules:/lib/modules:ro
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
    restart: unless-stopped
    networks:
      - mullvad-usa
    healthcheck:
      test: curl --fail https://am.i.mullvad.net/connected | grep "You are connected to Mullvad" || exit 1
      interval: 30s
      retries: 10
      start_period: 10s
      timeout: 2s
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=mullvad-usa"
      - "traefik.tcp.routers.mullvad-usa.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.mullvad-usa.entrypoints=mullvad-usa"
      - "traefik.tcp.routers.mullvad-usa.tls=false"
      - "traefik.tcp.routers.mullvad-usa.service=mullvad-usa"
      - "traefik.tcp.services.mullvad-usa.loadbalancer.server.port=4242"

  tailscale-mullvad-usa:
    container_name: tailscale-mullvad-usa
    image: tailscale/tailscale:latest
    volumes:
      - /services/mullvad-usa/tailscale:/var/lib/tailscale
      - /lib/modules:/lib/modules:ro
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    command: tailscaled --tun=userspace-networking
    restart: unless-stopped
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1
    depends_on:
      - wireguard-mullvad-usa
    network_mode: service:wireguard-mullvad-usa
    healthcheck:
      test: wget -qO- --no-verbose --tries=1 https://am.i.mullvad.net/connected | grep "You are connected to Mullvad" || exit 1
      interval: 30s
      retries: 10
      start_period: 10s
      timeout: 2s

  socks-proxy-mullvad-usa:
    container_name: socks-proxy-mullvad-usa
    build: ./go-socks5-proxy-docker
    environment:
      - PROXY_PORT=4242
    restart: unless-stopped
    depends_on:
      - wireguard-mullvad-usa
    network_mode: service:wireguard-mullvad-usa
    healthcheck:
      test: curl --fail https://am.i.mullvad.net/connected | grep "You are connected to Mullvad" || exit 1
      interval: 30s
      retries: 10
      start_period: 10s
      timeout: 2s

networks:
  mullvad-usa:
    name: mullvad-usa
    external: true