version: '3.9'
services:
  poste-io:
    image: docker.io/analogic/poste.io
    volumes:
      - /services/poste/data:/data
    ports:
      - "2025:25"
      - 2110:110 
      - 2143:143 
      - 2465:465 
      - 2587:587 
      - 2993:993 
      - 2995:995
    restart: unless-stopped
    networks:
      - poste
    environment:
      - TZ=America/New_York
      - HTTPS=OFF
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=poste"
      - "traefik.http.routers.poste.rule=Host(`mail.bspwr.com`)"
      - "traefik.http.routers.poste.entrypoints=websecure"
      - "traefik.http.routers.poste.tls=true"
      - "traefik.http.routers.poste.tls.certresolver=letsencrypt"
      - "traefik.http.routers.poste.service=poste"
      - "traefik.http.routers.poste.middlewares=default@file"
      - "traefik.http.services.poste.loadbalancer.server.port=80"

networks:
  poste:
    name: poste
    external: true