version: "3.9"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1420
      - PGID=1420
      - TZ=America/New_York
      - JELLYFIN_PublishedServerUrl=jellyfin.bspwr.com #optional
    volumes:
      - /services/jellyfin/config:/config:Z
      - /ocean/media/shows:/data/shows:z
      - /ocean/media/movies:/data/movies:z
      - /ocean/media/music:/data/music:z
      - /ocean/media/books:/data/books:z
      - /ocean/media/xxx:/data/xxx:z
    networks:
      - jellyfin
    restart: unless-stopped
    healthcheck:
      test: curl --fail localhost:8096 || exit 1
      interval: 10s
      retries: 6
      start_period: 10s
      timeout: 2s
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=jellyfin"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.bspwr.com`)"
      - "traefik.http.routers.jellyfin.entrypoints=websecure"
      - "traefik.http.routers.jellyfin.tls=true"
      - "traefik.http.routers.jellyfin.tls.certresolver=letsencrypt"
      - "traefik.http.routers.jellyfin.service=jellyfin"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"

networks:
  jellyfin:
    name: jellyfin
    external: true