version: "3.9"
services:
  projectsend:
    image: lscr.io/linuxserver/projectsend:latest
    container_name: projectsend
    environment:
      - PUID=1420
      - PGID=1420
      - TZ=America/New_York
      - MAX_UPLOAD=1024000
    volumes:
      - /services/projectsend/config:/config
      - /ocean/services/projectsend:/data/projectsend
    depends_on:
      - projectsend-mariadb
    restart: unless-stopped
    networks:
      - projectsend
    healthcheck:
      test: curl --fail localhost:80 || exit 1
      interval: 10s
      retries: 6
      start_period: 10s
      timeout: 2s
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=projectsend"
      - "traefik.http.routers.projectsend.rule=Host(`projectsend.bspwr.com`)"
      - "traefik.http.routers.projectsend.entrypoints=websecure"
      - "traefik.http.routers.projectsend.tls=true"
      - "traefik.http.routers.projectsend.tls.certresolver=myresolver"
      - "traefik.http.routers.projectsend.service=projectsend"
      - "traefik.http.services.projectsend.loadbalancer.server.port=80"

  projectsend-mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: projectsend-mariadb
    environment:
      - PUID=1420
      - PGID=1420
      - TZ=America/New_York
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=projectsend
      - MYSQL_USER=projectsend
      - MYSQL_PASSWORD=projectsend
    volumes:
      - /services/projectsend/mariadb:/config
    networks:
      - projectsend
    restart: unless-stopped
    healthcheck:
      test: nc -zv localhost 3306 || exit 1
      interval: 10s
      retries: 6
      start_period: 10s
      timeout: 2s

networks:
  projectsend:
    name: projectsend
    external: true