version: '3.9'
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /services/heimdall/config:/config
    restart: unless-stopped
    networks:
      - heimdall
    healthcheck:
      test: curl --fail localhost:80 || exit 1
      interval: 10s
      retries: 6
      start_period: 10s
      timeout: 2s
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=heimdall"
      - "traefik.http.routers.heimdall.rule=Host(`bspwr.com`, `heimdall.bspwr.com`)"
      - "traefik.http.routers.heimdall.entrypoints=websecure"
      - "traefik.http.routers.heimdall.tls=true"
      - "traefik.http.routers.heimdall.tls.certresolver=letsencrypt"
      - "traefik.http.routers.heimdall.service=heimdall"
      - "traefik.http.services.heimdall.loadbalancer.server.port=80"


networks:
  heimdall:
    name: heimdall
    external: true