version: "3.9"
services:
  blog:
    build: .
    container_name: blog
    restart: unless-stopped
    networks:
      - blog
    healthcheck:
      test: curl --fail localhost:80 || exit 1
      interval: 10s
      retries: 6
      start_period: 10s
      timeout: 2s
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=blog"
      - "traefik.http.routers.blog.rule=Host(`blog.bspwr.com`)"
      - "traefik.http.routers.blog.entrypoints=websecure"
      - "traefik.http.routers.blog.tls=true"
      - "traefik.http.routers.blog.tls.certresolver=letsencrypt"
      - "traefik.http.routers.blog.service=blog"
      - "traefik.http.services.blog.loadbalancer.server.port=80"

networks:
  blog:
    name: blog
    external: true