version: '3.9'
services:
  jenkins:
    build: .
    user: "1420:1420"
    container_name: jenkins
    restart: unless-stopped
    networks:
      - jenkins
    volumes:
      - /services/jenkins/home:/var/jenkins_home
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=jenkins"
      - "traefik.http.routers.jenkins.rule=Host(`jenkins.bspwr.com`)"
      - "traefik.http.routers.jenkins.entrypoints=websecure"
      - "traefik.http.routers.jenkins.tls=true"
      - "traefik.http.routers.jenkins.tls.certresolver=letsencrypt"
      - "traefik.http.routers.jenkins.service=jenkins"
      - "traefik.http.routers.jenkins.middlewares=default@file"
      - "traefik.http.services.jenkins.loadbalancer.server.port=8080"

  jenkins-docker: # 2375
    image: docker:20.10.17-dind-alpine3.16
    container_name: jenkins-docker
    privileged: yes
    environment:
    - DOCKER_TLS_CERTDIR=
    networks:
      - jenkins

networks:
  jenkins:
    name: jenkins
    external: true