version: "3.9"
services:
  traefik:
    image: traefik:v2.9
    container_name: traefik
    restart: unless-stopped
    ports:
      - target: 80 # Public HTTP Port
        published: 1080 # Outside port
        mode: host
        protocol: tcp
      - target: 443 # Public HTTPS Port
        published: 1443 # Outside port
        mode: host
        protocol: tcp
      - target: 4242 # Mullvad USA SOCKS Proxy
        published: 4242 # Outside port
        mode: host
        protocol: tcp
      - target: 6969 # Mullvad Sweden SOCKS Proxy
        published: 6969 # Outside port
        mode: host
        protocol: tcp
      - target: 4444 # I2P HTTP Proxy
        published: 4444 # Outside port
        mode: host
        protocol: tcp
      - target: 9050 # Tor SOCKS Proxy
        published: 9050 # Outside port
        mode: host
        protocol: tcp
      - target: 18089 # Monero Node
        published: 18089 # Outside port
        mode: host
        protocol: tcp
      - target: 25565 # Minecraft Server
        published: 25565 # Outside port
        mode: host
        protocol: tcp
      - target: 3478 # TURN Server TDP
        published: 3478 # Outside port
        mode: host
        protocol: tcp
      - target: 3478 # TURN Server UDP
        published: 3478 # Outside port
        mode: host
        protocol: udp
      - target: 2222 # Gitea SSH
        published: 2222 # Outside port
        mode: host
        protocol: udp
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - /services/traefik/letsencrypt:/etc/traefik/letsencrypt
      - /services/traefik/logs:/etc/traefik/logs
      - /services/traefik/traefik.yml:/etc/traefik/traefik.yml
      - /services/traefik/config.yml:/etc/traefik/config.yml
    networks:
      - arr
      - blog
      - filebrowser
      - gitea
      - headscale
      - heimdall
      - incognito
      - jellyfin
      - jenkins
      - lxdware
      - minecraft-atm7
      - minecraft-atm8
      - minecraft-enigmatica2
      - mullvad-sweden
      - mullvad-usa
      - nextcloud
      - photoprism
      - portainer
      - poste
      - projectsend
      - traefik
      - virt-manager
      - webdav
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.traefik.rule=Host(`traefik.local.bspwr.com`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.tls.certresolver=letsencrypt"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.middlewares=local-allowlist@file"

networks:
  arr:
    name: arr
    external: true
  blog:
    name: blog
    external: true
  filebrowser:
    name: filebrowser
    external: true
  gitea:
    name: gitea
    external: true
  headscale:
    name: headscale
    external: true
  heimdall:
    name: heimdall
    external: true
  incognito:
    name: incognito
    external: true
  jellyfin:
    name: jellyfin
    external: true
  jenkins:
    name: jenkins
    external: true
  lxdware:
    name: lxdware
    external: true
  minecraft-atm7:
    name: minecraft-atm7
    external: true
  minecraft-atm8:
    name: minecraft-atm8
    external: true
  minecraft-enigmatica2:
    name: minecraft-enigmatica2
    external: true
  mullvad-sweden:
    name: mullvad-sweden
    external: true
  mullvad-usa:
    name: mullvad-usa
    external: true
  nextcloud:
    name: nextcloud
    external: true
  photoprism:
    name: photoprism
    external: true
  portainer:
    name: portainer
    external: true
  poste:
    name: poste
    external: true
  projectsend:
    name: projectsend
    external: true
  traefik:
    name: traefik
    external: true
  virt-manager:
    name: virt-manager
    external: true
  webdav:
    name: webdav
    external: true