version: "3.9"
services:
  traefik:
    image: traefik:v2.9
    container_name: traefik
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true" # enable web UI
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.forwardedHeaders.trustedIPs=127.0.0.1/32,10.0.0.0/8,192.168.0.0/16,172.16.0.0/12"
      - "--entryPoints.mullvad-usa.address=:4242"
      - "--entryPoints.mullvad-sweden.address=:6969"
      - "--entryPoints.i2p-proxy.address=:4444"
      - "--entryPoints.tor-proxy.address=:9050"
      - "--entryPoints.monero-node.address=:18089"
      - "--entryPoints.minecraft.address=:25565"
      - "--entryPoints.turn-server.address=:3478"
      - "--entryPoints.turn-server-udp.address=:3478/udp"
      - "--entryPoints.gitea-ssh.address=:2222"
      # cert resolver
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.caserver=https://acme-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=bree@bspwr.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    restart: unless-stopped
    ports:
      - target: 80 # Public HTTP Port
        published: 1080 # Outside port
        mode: host
        protocol: tcp
      - target: 443 # Public HTTPS Port
        published: 1443 # Outside port
        mode: host
        protocol: tcp
      - target: 4242 # Mullvad USA SOCKS Proxy
        published: 4242 # Outside port
        mode: host
        protocol: tcp
      - target: 6969 # Mullvad Sweden SOCKS Proxy
        published: 6969 # Outside port
        mode: host
        protocol: tcp
      - target: 4444 # I2P HTTP Proxy
        published: 4444 # Outside port
        mode: host
        protocol: tcp
      - target: 9050 # Tor SOCKS Proxy
        published: 9050 # Outside port
        mode: host
        protocol: tcp
      - target: 18089 # Monero Node
        published: 18089 # Outside port
        mode: host
        protocol: tcp
      - target: 25565 # Minecraft Server
        published: 25565 # Outside port
        mode: host
        protocol: tcp
      - target: 3478 # TURN Server TDP
        published: 3478 # Outside port
        mode: host
        protocol: tcp
      - target: 3478 # TURN Server UDP
        published: 3478 # Outside port
        mode: host
        protocol: udp
      - target: 2222 # Gitea SSH
        published: 2222 # Outside port
        mode: host
        protocol: udp
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - /services/traefik/letsencrypt:/letsencrypt
    networks:
      - arr
      - blog
      - filebrowser
      - gitea
      - headscale
      - heimdall
      - incognito
      - jellyfin
      - jenkins
      - lxdware
      - minecraft-atm7
      - minecraft-atm8
      - minecraft-enigmatica2
      - mullvad-sweden
      - mullvad-usa
      - nextcloud
      - photoprism
      - portainer
      - poste
      - projectsend
      - traefik
      - virt-manager
      - webdav
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.traefik.rule=Host(`traefik.local.bspwr.com`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.tls.certresolver=myresolver"
      - "traefik.http.routers.traefik.service=traefik"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.ip-allowlist.ipwhitelist.sourcerange=162.245.135.173, 100.64.0.1/32, 172.17.0.0/12"
      - "traefik.http.routers.traefik.middlewares=ip-allowlist@docker"

networks:
  arr:
    name: arr
    external: true
  blog:
    name: blog
    external: true
  filebrowser:
    name: filebrowser
    external: true
  gitea:
    name: gitea
    external: true
  headscale:
    name: headscale
    external: true
  heimdall:
    name: heimdall
    external: true
  incognito:
    name: incognito
    external: true
  jellyfin:
    name: jellyfin
    external: true
  jenkins:
    name: jenkins
    external: true
  lxdware:
    name: lxdware
    external: true
  minecraft-atm7:
    name: minecraft-atm7
    external: true
  minecraft-atm8:
    name: minecraft-atm8
    external: true
  minecraft-enigmatica2:
    name: minecraft-enigmatica2
    external: true
  mullvad-sweden:
    name: mullvad-sweden
    external: true
  mullvad-usa:
    name: mullvad-usa
    external: true
  nextcloud:
    name: nextcloud
    external: true
  photoprism:
    name: photoprism
    external: true
  portainer:
    name: portainer
    external: true
  poste:
    name: poste
    external: true
  projectsend:
    name: projectsend
    external: true
  traefik:
    name: traefik
    external: true
  virt-manager:
    name: virt-manager
    external: true
  webdav:
    name: webdav
    external: true