version: "3.9"
services:
  nginx-proxy-manager:
    build: .
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - target: 80 # Public HTTP Port
        published: 1080 # Outside port
        mode: host
        protocol: tcp
      - target: 443 # Public HTTPS Port
        published: 1443 # Outside port
        mode: host
        protocol: tcp
      - target: 4242 # Mullvad USA SOCKS Proxy
        published: 4242 # Outside port
        mode: host
        protocol: tcp
      - target: 6969 # Mullvad Sweden SOCKS Proxy
        published: 6969 # Outside port
        mode: host
        protocol: tcp
      - target: 4444 # I2P HTTP Proxy
        published: 4444 # Outside port
        mode: host
        protocol: tcp
      - target: 9050 # Tor SOCKS Proxy
        published: 9050 # Outside port
        mode: host
        protocol: tcp
      - target: 18089 # Monero Node
        published: 18089 # Outside port
        mode: host
        protocol: tcp
      - target: 25565 # Minecraft Server
        published: 25565 # Outside port
        mode: host
        protocol: tcp
    volumes:
      - /services/nginx-proxy-manager/data:/data
      - /services/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
      # Uncomment this if IPv6 is not enabled on your host
      DISABLE_IPV6: 'true'
    networks:
      - arr
      - blog
      - filebrowser
      - headscale
      - heimdall
      - incognito
      - jellyfin
      - lxdware
      - minecraft-atm7
      - minecraft-atm8
      - mullvad-sweden
      - mullvad-usa
      - nextcloud
      - nginx-proxy-manager
      - portainer
      - poste
      - projectsend
      - virt-manager
      - webdav
    healthcheck:
      test: curl --fail localhost:81 || exit 1
      interval: 10s
      retries: 6
      start_period: 10s
      timeout: 1s

  goaccess:
    image: xavierh/goaccess-for-nginxproxymanager:latest
    container_name: goaccess
    restart: unless-stopped
    networks:
      - nginx-proxy-manager
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/New_York
      - DEBUG=False
      - EXCLUDE_IPS=127.0.0.1
      - LOG_TYPE=NPM
    volumes:
    - /services/nginx-proxy-manager/data/logs:/opt/log
    - /services/nginx-proxy-manager/goaccess:/opt/custom
    healthcheck:
      test: curl --fail localhost:7880 || exit 1
      interval: 10s
      retries: 6
      start_period: 10s
      timeout: 1s

networks:
  arr:
    name: arr
    external: true
  portainer:
    name: portainer
    external: true
  blog:
    name: blog
    external: true
  filebrowser:
    name: filebrowser
    external: true
  headscale:
    name: headscale
    external: true
  heimdall:
    name: heimdall
    external: true
  incognito:
    name: incognito
    external: true
  jellyfin:
    name: jellyfin
    external: true
  lxdware:
    name: lxdware
    external: true
  minecraft-atm7:
    name: minecraft-atm7
    external: true
  minecraft-atm8:
    name: minecraft-atm8
    external: true
  mullvad-sweden:
    name: mullvad-sweden
    external: true
  mullvad-usa:
    name: mullvad-usa
    external: true
  nextcloud:
    name: nextcloud
    external: true
  nginx-proxy-manager:
    name: nginx-proxy-manager
    external: true
  poste:
    name: poste
    external: true
  projectsend:
    name: projectsend
    external: true
  virt-manager:
    name: virt-manager
    external: true
  webdav:
    name: webdav
    external: true