version: '3.9'
services:
  nfs-server:
    image: erichough/nfs-server
    container_name: nfs-server
    cap_add:
      - SYS_ADMIN
    volumes:
      - /ocean/backup/megakill:/export/backup/megakill
      - /ocean/backup/overkill:/export/backup/overkill
      - /ocean/nas/bree:/export/nas/bree
    environment:
      NFS_VERSION: 4.2
      NFS_DISABLE_VERSION_3: true
      NFS_SERVER_THREAD_COUNT: 48
      NFS_EXPORT_0: /export/backup/megakill  100.64.0.0/10(rw,nohide,insecure,no_subtree_check,no_root_squash)
      NFS_EXPORT_1: /export/backup/overkill  100.64.0.0/10(rw,nohide,insecure,no_subtree_check,no_root_squash)
      NFS_EXPORT_2: /export/nas/bree         100.64.0.0/10(rw,nohide,insecure,no_subtree_check)
    ports:
     - 2049:2049
    restart: unless-stopped