version: '3.9'
services:
  nfs-server:
    image: erichough/nfs-server
    container_name: nfs-server
    cap_add:
      - SYS_ADMIN
    volumes:
      - /ocean/nas/bree:/nas/bree
      - /ocean/backup/megakill:/backup/megakill
      - /ocean/backup/overkill:/backup/overkill
      - /ocean/images:/images
    environment:
      NFS_VERSION: 4.2
      NFS_DISABLE_VERSION_3: true
      NFS_SERVER_THREAD_COUNT: 48
      NFS_EXPORT_0: /nas/bree         100.64.0.0/10(rw,nohide,insecure,no_subtree_check)
      NFS_EXPORT_1: /backup/megakill  100.64.0.0/10(rw,nohide,insecure,no_subtree_check,no_root_squash)
      NFS_EXPORT_2: /backup/overkill  100.64.0.0/10(rw,nohide,insecure,no_subtree_check,no_root_squash)
      NFS_EXPORT_3: /images           100.64.0.0/10(rw,nohide,insecure,no_subtree_check,no_root_squash)
    network_mode: host # 2049
    restart: unless-stopped