version: '3.9'
services:
  lxdware-dashboard:
    build: ./docker
    container_name: lxdware-dashboard
    volumes:
      - /services/lxdware/lxdware:/var/lxdware
    networks:
      - lxdware
    restart: unless-stopped
    healthcheck:
      test: curl --fail localhost:80 || exit 1
      interval: 10s
      retries: 6
      start_period: 10s
      timeout: 2s
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=lxdware"
      - "traefik.http.routers.lxdware.rule=Host(`lxd.local.bspwr.com`)"
      - "traefik.http.routers.lxdware.entrypoints=websecure"
      - "traefik.http.routers.lxdware.tls=true"
      - "traefik.http.routers.lxdware.tls.certresolver=myresolver"
      - "traefik.http.routers.lxdware.service=lxdware"
      - "traefik.http.services.lxdware.loadbalancer.server.port=80"
      - "traefik.http.middlewares.ip-allowlist.ipwhitelist.sourcerange=162.245.135.173, 100.64.0.1/32, 172.17.0.0/12"
      - "traefik.http.routers.lxdware.middlewares=ip-allowlist@docker"

networks:
  lxdware:
    name: lxdware
    external: true