version: "3.9"
services:
  filebrowser:
    image: filebrowser/filebrowser:s6
    container_name: filebrowser
    hostname: filebrowser
    environment:
      - PUID=1420
      - PGID=1420
      - TZ=America/New_York
    volumes:
      - /ocean/services/filebrowser:/srv
      - /services/filebrowser/database:/database
      - /services/filebrowser/config:/config
    networks:
      - filebrowser
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=filebrowser"
      - "traefik.http.routers.filebrowser.rule=Host(`files.bspwr.com`)"
      - "traefik.http.routers.filebrowser.entrypoints=websecure"
      - "traefik.http.routers.filebrowser.tls=true"
      - "traefik.http.routers.filebrowser.tls.certresolver=letsencrypt"
      - "traefik.http.routers.filebrowser.service=filebrowser"
      - "traefik.http.services.filebrowser.loadbalancer.server.port=80"

  filebrowser-downloads:
    image: filebrowser/filebrowser:s6
    container_name: filebrowser-downloads
    hostname: filebrowser-downloads
    environment:
      - PUID=1420
      - PGID=1420
      - TZ=America/New_York
    volumes:
      - /ocean/downloads:/srv:ro
      - /services/filebrowser/database-downloads:/database
      - /services/filebrowser/config-downloads:/config
    networks:
      - filebrowser
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=filebrowser"
      - "traefik.http.routers.filebrowser-downloads.rule=Host(`downloads.bspwr.com`)"
      - "traefik.http.routers.filebrowser-downloads.entrypoints=websecure"
      - "traefik.http.routers.filebrowser-downloads.tls=true"
      - "traefik.http.routers.filebrowser-downloads.tls.certresolver=letsencrypt"
      - "traefik.http.routers.filebrowser-downloads.service=filebrowser-downloads"
      - "traefik.http.services.filebrowser-downloads.loadbalancer.server.port=80"

  filebrowser-media:
    image: filebrowser/filebrowser:s6
    container_name: filebrowser-media
    hostname: filebrowser-media
    environment:
      - PUID=1420
      - PGID=1420
      - TZ=America/New_York
    volumes:
      - /ocean/media/shows:/srv/shows:ro
      - /ocean/media/movies:/srv/movies:ro
      - /ocean/media/music:/srv/music:ro
      - /ocean/media/books:/srv/books:ro
      - /services/filebrowser/database-media:/database
      - /services/filebrowser/config-media:/config
    networks:
      - filebrowser
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=filebrowser"
      - "traefik.http.routers.filebrowser-media.rule=Host(`media.bspwr.com`)"
      - "traefik.http.routers.filebrowser-media.entrypoints=websecure"
      - "traefik.http.routers.filebrowser-media.tls=true"
      - "traefik.http.routers.filebrowser-media.tls.certresolver=letsencrypt"
      - "traefik.http.routers.filebrowser-media.service=filebrowser-media"
      - "traefik.http.services.filebrowser-media.loadbalancer.server.port=80"

networks:
  filebrowser:
    name: filebrowser
    external: true