version: "3.9"
services:
  wireguard-mullvad-sweden:
    image: ghcr.io/linuxserver/wireguard
    container_name: wireguard-mullvad-sweden
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1420
      - PGID=1420
      - TZ=America/New_York
    volumes:
      - /services/mullvad-sweden/wireguard:/config:Z
      - /lib/modules:/lib/modules:ro
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
    restart: unless-stopped
    networks:
      - mullvad-sweden
    healthcheck:
      test: curl --fail https://am.i.mullvad.net/connected | grep "You are connected to Mullvad" || exit 1
      interval: 30s
      retries: 10
      start_period: 10s
      timeout: 2s
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=mullvad-sweden"
      - "traefik.tcp.routers.mullvad-sweden.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.mullvad-sweden.entrypoints=mullvad-sweden"
      - "traefik.tcp.routers.mullvad-sweden.tls=false"
      - "traefik.tcp.routers.mullvad-sweden.service=mullvad-sweden"
      - "traefik.tcp.services.mullvad-sweden.loadbalancer.server.port=6969"

  tailscale-mullvad-sweden:
    container_name: tailscale-mullvad-sweden
    image: tailscale/tailscale:latest
    volumes:
      - /services/mullvad-sweden/tailscale:/var/lib/tailscale
      - /lib/modules:/lib/modules:ro
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    command: tailscaled --tun=userspace-networking
    restart: unless-stopped
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1
    depends_on:
      - wireguard-mullvad-sweden
    network_mode: service:wireguard-mullvad-sweden
    healthcheck:
      test: wget -qO- --no-verbose --tries=1 https://am.i.mullvad.net/connected | grep "You are connected to Mullvad" || exit 1
      interval: 30s
      retries: 10
      start_period: 10s
      timeout: 2s

  socks-proxy-mullvad-sweden:
    container_name: socks-proxy-mullvad-sweden
    build: ./go-socks5-proxy-docker
    environment:
      - PROXY_PORT=6969
    restart: unless-stopped
    depends_on:
      - wireguard-mullvad-sweden
    network_mode: service:wireguard-mullvad-sweden
    healthcheck:
      test: curl --fail https://am.i.mullvad.net/connected | grep "You are connected to Mullvad" || exit 1
      interval: 30s
      retries: 10
      start_period: 10s
      timeout: 2s

networks:
  mullvad-sweden:
    name: mullvad-sweden
    external: true