version: "3.9"
services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:26.0.0
    container_name: nextcloud
    environment:
      - PUID=1420
      - PGID=1420
      - TZ=America/New_York
    volumes:
      - /services/nextcloud/config:/config
      - /ocean/services/nextcloud:/data
    restart: unless-stopped
    depends_on:
      - nextcloud-mariadb
      - nextcloud-collabora
      - nextcloud-redis
    networks:
      - nextcloud
    healthcheck:
      test: curl --fail --insecure https://localhost || exit 1
      interval: 10s
      retries: 6
      start_period: 10s
      timeout: 2s
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=nextcloud"
      - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.bspwr.com`)"
      - "traefik.http.routers.nextcloud.priority=1"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.routers.nextcloud.tls=true"
      - "traefik.http.routers.nextcloud.tls.certresolver=letsencrypt"
      - "traefik.http.routers.nextcloud.service=nextcloud"
      - "traefik.http.routers.nextcloud.middlewares=nextcloud_redirectregex, default@file"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
      - "traefik.http.middlewares.nextcloud_redirectregex.redirectregex.permanent=true"
      - "traefik.http.middlewares.nextcloud_redirectregex.redirectregex.regex=https://(.*)/.well-known/(?:card|cal)dav"
      - "traefik.http.middlewares.nextcloud_redirectregex.redirectregex.replacement=https://$${1}/remote.php/dav"

  nextcloud-mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: nextcloud-mariadb
    environment:
      - PUID=1420
      - PGID=1420
      - TZ=America/New_York
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud
    volumes:
      - /services/nextcloud/mariadb:/config
    restart: unless-stopped
    networks:
      - nextcloud
    healthcheck:
      test: nc -zv localhost 3306 || exit 1
      interval: 10s
      retries: 6
      start_period: 10s
      timeout: 2s

  nextcloud-collabora:
    image: docker.io/collabora/code:latest
    container_name: nextcloud-collabora
    restart: unless-stopped
    networks:
      - nextcloud
    environment:
      - "extra_params=--o:ssl.enable=false --o:ssl.termination=true"
    healthcheck:
      test: curl --fail http://localhost:9980 || exit 1
      interval: 10s
      retries: 6
      start_period: 10s
      timeout: 2s
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=nextcloud"
      - "traefik.http.routers.collabora.rule=Host(`collabora.bspwr.com`)"
      - "traefik.http.routers.collabora.entrypoints=websecure"
      - "traefik.http.routers.collabora.tls=true"
      - "traefik.http.routers.collabora.tls.certresolver=letsencrypt"
      - "traefik.http.routers.collabora.service=collabora"
      - "traefik.http.routers.collabora.middlewares=default@file"
      - "traefik.http.services.collabora.loadbalancer.server.port=9980"

  nextcloud-redis:
    image: docker.io/redis:latest
    container_name: nextcloud-redis
    environment:
      - PUID=1420
      - PGID=1420
      - TZ=America/New_York
    volumes:
      - /services/nextcloud/redis:/data
    command: redis-server --requirepass nextcloud
    restart: unless-stopped
    networks:
      - nextcloud
    healthcheck:
      test: redis-cli -a nextcloud ping | grep PONG
      interval: 10s
      retries: 6
      start_period: 10s
      timeout: 2s

  nextcloud-client-push:
    image: docker.io/miles170/notify_push:latest
    container_name: nextcloud-client-push
    restart: unless-stopped
    volumes:
      - /services/nextcloud/config/www/nextcloud/config/config.php:/config.php:ro
    command: /notify_push /config.php
    networks:
      - nextcloud
    environment:
      - NEXTCLOUD_URL=http://nextcloud
    healthcheck:
      test: ["CMD", "/notify_push", "--dump-config", "/config.php"]
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=nextcloud"
      - "traefik.http.routers.nextcloud-client-push.rule=Host(`nextcloud.bspwr.com`) && PathPrefix(`/push`)"
      - "traefik.http.routers.nextcloud-client-push.priority=2"
      - "traefik.http.routers.nextcloud-client-push.entrypoints=websecure"
      - "traefik.http.routers.nextcloud-client-push.tls=true"
      - "traefik.http.routers.nextcloud-client-push.tls.certresolver=letsencrypt"
      - "traefik.http.routers.nextcloud-client-push.service=nextcloud-client-push"
      - "traefik.http.services.nextcloud-client-push.loadbalancer.server.port=7867"
      - "traefik.http.routers.nextcloud-client-push.middlewares=nextcloud-client-push_strip,default@file"
      - "traefik.http.middlewares.nextcloud-client-push_strip.stripprefix.prefixes=/push"

networks:
  nextcloud:
    name: nextcloud
    external: true