version: "3.9"
services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:26.0.0
    container_name: nextcloud
    environment:
      - PUID=1420
      - PGID=1420
      - TZ=America/New_York
      - TRUSTED_PROXIES=172.17.0.0/12 172.16.128.3
    volumes:
      - /services/nextcloud/config:/config
      - /ocean/services/nextcloud:/data
    restart: unless-stopped
    depends_on:
      - nextcloud-mariadb
      - nextcloud-collabora
      - nextcloud-redis
    networks:
      - nextcloud
    healthcheck:
      test: curl --fail --insecure https://localhost || exit 1
      interval: 10s
      retries: 6
      start_period: 10s
      timeout: 2s
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=nextcloud"
      - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.bspwr.com`)"
      - "traefik.http.routers.nextcloud.priority=1"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.routers.nextcloud.tls=true"
      - "traefik.http.routers.nextcloud.tls.certresolver=letsencrypt"
      - "traefik.http.routers.nextcloud.service=nextcloud"
      - "traefik.http.routers.nextcloud.middlewares=nextcloud_redirectregex, default@file"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
      - "traefik.http.middlewares.nextcloud_redirectregex.redirectregex.permanent=true"
      - "traefik.http.middlewares.nextcloud_redirectregex.redirectregex.regex=https://(.*)/.well-known/(?:card|cal)dav"
      - "traefik.http.middlewares.nextcloud_redirectregex.redirectregex.replacement=https://$${1}/remote.php/dav"

  nextcloud-mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: nextcloud-mariadb
    environment:
      - PUID=1420
      - PGID=1420
      - TZ=America/New_York
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud
    volumes:
      - /services/nextcloud/mariadb:/config
    restart: unless-stopped
    networks:
      - nextcloud
    healthcheck:
      test: nc -zv localhost 3306 || exit 1
      interval: 10s
      retries: 6
      start_period: 10s
      timeout: 2s

  nextcloud-collabora:
    image: collabora/code
    container_name: nextcloud-collabora
    restart: unless-stopped
    networks:
      - nextcloud
    environment:
      - "extra_params=--o:ssl.enable=false --o:ssl.termination=true"
    healthcheck:
      test: curl --fail http://localhost:9980 || exit 1
      interval: 10s
      retries: 6
      start_period: 10s
      timeout: 2s
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=nextcloud"
      - "traefik.http.routers.collabora.rule=Host(`collabora.bspwr.com`)"
      - "traefik.http.routers.collabora.entrypoints=websecure"
      - "traefik.http.routers.collabora.tls=true"
      - "traefik.http.routers.collabora.tls.certresolver=letsencrypt"
      - "traefik.http.routers.collabora.service=collabora"
      - "traefik.http.routers.collabora.middlewares=default@file"
      - "traefik.http.services.collabora.loadbalancer.server.port=9980"

  nextcloud-redis:
    image: redis
    container_name: nextcloud-redis
    environment:
      - PUID=1420
      - PGID=1420
      - TZ=America/New_York
    volumes:
      - /services/nextcloud/redis:/data
    command: redis-server --requirepass nextcloud
    restart: unless-stopped
    networks:
      - nextcloud
    healthcheck:
      test: redis-cli -a nextcloud ping | grep PONG
      interval: 10s
      retries: 6
      start_period: 10s
      timeout: 2s

  nextcloud-client-push:
    build: client-push
    container_name: nextcloud-client-push
    restart: unless-stopped
    volumes:
      - /services/nextcloud/config/www/nextcloud/config/config.php:/config.php:ro
    command: /notify_push /config.php
    networks:
      - nextcloud
    environment:
      - NEXTCLOUD_URL=http://nextcloud
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=nextcloud"
      - "traefik.http.routers.nextcloud-client-push.rule=Host(`nextcloud.bspwr.com`) && PathPrefix(`/push`)"
      - "traefik.http.routers.nextcloud-client-push.priority=2"
      - "traefik.http.routers.nextcloud-client-push.entrypoints=websecure"
      - "traefik.http.routers.nextcloud-client-push.tls=true"
      - "traefik.http.routers.nextcloud-client-push.tls.certresolver=letsncrypt"
      - "traefik.http.routers.nextcloud-client-push.service=nextcloud-client-push"
      - "traefik.http.services.nextcloud-client-push.loadbalancer.server.port=7867"
      - "traefik.http.routers.nextcloud-client-push.middlewares=nextcloud-client-push_strip,default@file"
      - "traefik.http.middlewares.nextcloud-client-push_strip.stripprefix.prefixes=/push"

  # TODO: fix this, it's still borked
  # nextcloud-spreed-nginx:
  #   image: nginx
  #   container_name:  nextcloud-spreed-nginx
  #   volumes:
  #     - /services/nextcloud/spreed/nginx.conf:/etc/nginx/nginx.conf:ro
  #   networks:
  #     - nextcloud
  #   restart: unless-stopped
  #   depends_on:
  #     - nextcloud-spreed-backend
  #     - nextcloud-spreed-nats
  #     - nextcloud-spreed-janus
  #     - nextcloud-spreed-coturn
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.docker.network=nextcloud"
  #     - "traefik.http.routers.nextcloud-spreed-backend.rule=Host(`signaling.bspwr.com`)"
  #     - "traefik.http.routers.nextcloud-spreed-backend.entrypoints=websecure"
  #     - "traefik.http.routers.nextcloud-spreed-backend.tls=true"
  #     - "traefik.http.routers.nextcloud-spreed-backend.tls.certresolver=letsencrypt"
  #     - "traefik.http.routers.nextcloud-spreed-backend.service=nextcloud-spreed-backend"
  #     - "traefik.http.services.nextcloud-spreed-backend.loadbalancer.server.port=80"
  #     - "traefik.http.middlewares.spreed_headers.headers.customRequestHeaders.X-Forwarded-Proto=https"
  #     - "traefik.http.routers.nextcloud-spreed-backend.middlewares=spreed_headers"

  # nextcloud-spreed-backend:
  #   container_name: nextcloud-spreed-backend
  #   build: spreed
  #   volumes:
  #     - /services/nextcloud/spreed/server.conf:/config/server.conf:ro
  #   networks:
  #     - nextcloud
  #   restart: unless-stopped
  #   depends_on:
  #     - nextcloud-spreed-nats
  #     - nextcloud-spreed-janus
  #     - nextcloud-spreed-coturn
  #   healthcheck:
  #     test: wget -qO- localhost:8080 2>&1 | grep 404 || exit 1
  #     interval: 10s
  #     retries: 6
  #     start_period: 10s
  #     timeout: 2s
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.docker.network=nextcloud"
  #     - "traefik.http.routers.nextcloud-spreed-backend.rule=Host(`signaling.bspwr.com`)"
  #     - "traefik.http.routers.nextcloud-spreed-backend.entrypoints=websecure"
  #     - "traefik.http.routers.nextcloud-spreed-backend.tls=true"
  #     - "traefik.http.routers.nextcloud-spreed-backend.tls.certresolver=letsencrypt"
  #     - "traefik.http.routers.nextcloud-spreed-backend.service=nextcloud-spreed-backend"
  #     - "traefik.http.services.nextcloud-spreed-backend.loadbalancer.server.port=8080"
  #     - "traefik.http.middlewares.spreed_headers.headers.customRequestHeaders.X-Forwarded-Proto=https"
  #     - "traefik.http.routers.nextcloud-spreed-backend.middlewares=spreed_headers"

  # nextcloud-spreed-nats:
  #   container_name: nextcloud-spreed-nats
  #   image: nats:2.1
  #   volumes:
  #     - /services/nextcloud/spreed/gnatsd.conf:/config/gnatsd.conf:ro
  #   command: ["-c", "/config/gnatsd.conf"]
  #   networks:
  #     - nextcloud
  #   restart: unless-stopped

  # nextcloud-spreed-janus:
  #   container_name: nextcloud-spreed-janus
  #   build: janus
  #   command: ["janus", "--full-trickle"]
  #   networks:
  #     - nextcloud
  #   restart: unless-stopped
  #   healthcheck:
  #     test: curl localhost:8188 || exit 1
  #     interval: 10s
  #     retries: 6
  #     start_period: 10s
  #     timeout: 2s

  nextcloud-spreed-coturn:
    container_name: nextcloud-spreed-coturn
    image: coturn/coturn
    volumes:
      - /services/nextcloud/spreed/turnserver.conf:/etc/coturn/turnserver.conf:ro
    networks:
      - nextcloud
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=nextcloud"
      - "traefik.tcp.routers.nextcloud-spreed-coturn.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.nextcloud-spreed-coturn.entrypoints=turn-server"
      - "traefik.tcp.routers.nextcloud-spreed-coturn.tls=false"
      - "traefik.tcp.routers.nextcloud-spreed-coturn.service=nextcloud-spreed-coturn"
      - "traefik.tcp.services.nextcloud-spreed-coturn.loadbalancer.server.port=3478"
      - "traefik.udp.routers.nextcloud-spreed-coturn.entrypoints=turn-server-udp"
      - "traefik.udp.routers.nextcloud-spreed-coturn.service=nextcloud-spreed-coturn"
      - "traefik.udp.services.nextcloud-spreed-coturn.loadbalancer.server.port=3478"

networks:
  nextcloud:
    name: nextcloud
    external: true