version: '3.9'
services:
  headscale:
    image: headscale/headscale:0.21
    container_name: headscale
    volumes:
      - /services/headscale/config:/etc/headscale
      - /services/headscale/data:/var/lib/headscale
    networks:
      - headscale
    command: headscale serve
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=headscale"
      - "traefik.http.routers.headscale.rule=Host(`headscale.bspwr.com`) && PathPrefix(`/`)"
      - "traefik.http.routers.headscale.entrypoints=websecure"
      - "traefik.http.routers.headscale.tls=true"
      - "traefik.http.routers.headscale.tls.certresolver=letsencrypt"
      - "traefik.http.routers.headscale.service=headscale"
      - "traefik.http.routers.headscale.middlewares=default@file"
      - "traefik.http.services.headscale.loadbalancer.server.port=8080"

  headscale-ui:
    image: ghcr.io/gurucomputing/headscale-ui:latest
    restart: unless-stopped
    container_name: headscale-ui
    networks:
      - headscale
    healthcheck:
      test: wget -qO- --no-verbose --tries=1 --no-check-certificate https://localhost:443 || exit 1
      interval: 10s
      retries: 6
      start_period: 10s
      timeout: 2s
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=headscale"
      - "traefik.http.routers.headscale-ui.rule=Host(`headscale.bspwr.com`) && PathPrefix(`/web`)"
      - "traefik.http.routers.headscale-ui.entrypoints=websecure"
      - "traefik.http.routers.headscale-ui.tls=true"
      - "traefik.http.routers.headscale-ui.tls.certresolver=letsencrypt"
      - "traefik.http.routers.headscale-ui.service=headscale-ui"
      - "traefik.http.routers.headscale-ui.middlewares=default@file"
      - "traefik.http.services.headscale-ui.loadbalancer.server.port=80"

networks:
  headscale:
    name: headscale
    external: true