version: '3.9'
services:
  minecraft-atm8-rcon:
    image: docker.io/itzg/rcon
    container_name: minecraft-atm8-rcon
    environment:
      RWA_USERNAME: admin
      RWA_PASSWORD: 1337taco
      RWA_ADMIN: "true"
      # is referring to the hostname of minecraft container
      RWA_RCON_HOST: minecraft-atm8
      # needs to match the password configured for the container, which is 'minecraft' by default
      RWA_RCON_PASSWORD: minecraft
      RWA_WEBSOCKET_URL_SSL: "wss://minecraft-rcon.bspwr.com/websocket"
      RWA_WEBSOCKET_URL: "ws://minecraft-rcon.bspwr.com/websocket"
    networks:
      - minecraft-atm8
    volumes:
      - /services/minecraft-atm8/rcon-web-db:/opt/rcon-web-admin/db
    depends_on:
      - minecraft-atm8
    restart: unless-stopped
    healthcheck:
      test: curl --fail localhost:4326 || exit 1
      interval: 10s
      retries: 6
      start_period: 10s
      timeout: 1s
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=minecraft-atm8"
      - "traefik.http.routers.minecraft-rcon.rule=Host(`minecraft-rcon.bspwr.com`)"
      - "traefik.http.routers.minecraft-rcon.entrypoints=websecure"
      - "traefik.http.routers.minecraft-rcon.tls=true"
      - "traefik.http.routers.minecraft-rcon.tls.certresolver=letsencrypt"
      - "traefik.http.routers.minecraft-rcon.service=minecraft-rcon"
      - "traefik.http.services.minecraft-rcon.loadbalancer.server.port=4326"
      - "traefik.http.routers.minecraft-rcon-ws.rule=Host(`minecraft-rcon.bspwr.com`) && PathPrefix(`/websocket`)"
      - "traefik.http.routers.minecraft-rcon-ws.entrypoints=websecure"
      - "traefik.http.routers.minecraft-rcon-ws.tls=true"
      - "traefik.http.routers.minecraft-rcon-ws.tls.certresolver=letsencrypt"
      - "traefik.http.routers.minecraft-rcon-ws.service=minecraft-rcon-ws"
      - "traefik.http.services.minecraft-rcon-ws.loadbalancer.server.port=4327"
      - "traefik.http.routers.minecraft-rcon-ws.middlewares=minecraft-rcon-ws_strip"
      - "traefik.http.middlewares.minecraft-rcon-ws_strip.stripprefix.prefixes=/websocket"

  minecraft-atm8:
    image: docker.io/itzg/minecraft-server
    container_name: minecraft-atm8
    hostname: minecraft-atm8
    networks:
      - minecraft-atm8
    volumes:
      - /services/minecraft-atm8/data:/data
    environment:
      EULA: "TRUE"
      VERSION: "1.19.2"
      TYPE: "FORGE"
      FORGEVERSION: "43.1.55"
      INIT_MEMORY: "4G"
      MAX_MEMORY: "12G"
    stdin_open: true
    tty: true
    restart: unless-stopped
    healthcheck:
      test: mc-health
      interval: 10s
      retries: 6
      start_period: 10m
      timeout: 1s
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=minecraft-atm8"
      - "traefik.tcp.routers.minecraft.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.minecraft.entrypoints=minecraft"
      - "traefik.tcp.routers.minecraft.tls=false"
      - "traefik.tcp.routers.minecraft.service=minecraft"
      - "traefik.tcp.services.minecraft.loadbalancer.server.port=25565"

networks:
  minecraft-atm8:
    name: minecraft-atm8
    external: true