version: "3.9"
services:
  wireguard-arr:
    image: ghcr.io/linuxserver/wireguard
    container_name: wireguard-arr
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1420
      - PGID=1420
      - TZ=America/New_York
    volumes:
      - /services/arr/wireguard:/config:Z
      - /lib/modules:/lib/modules:ro
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
    restart: unless-stopped
    networks:
      - arr
    healthcheck:
      test: curl --fail https://am.i.mullvad.net/connected | grep "You are connected to Mullvad" || exit 1
      interval: 30s
      retries: 10
      start_period: 10s
      timeout: 2s
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=arr"
      # Deluge
      - "traefik.http.routers.deluge.rule=Host(`deluge.bspwr.com`)"
      - "traefik.http.routers.deluge.entrypoints=websecure"
      - "traefik.http.routers.deluge.tls=true"
      - "traefik.http.routers.deluge.tls.certresolver=myresolver"
      - "traefik.http.routers.deluge.service=deluge"
      - "traefik.http.services.deluge.loadbalancer.server.port=8112"
      # Sonarr
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.bspwr.com`)"
      - "traefik.http.routers.sonarr.entrypoints=websecure"
      - "traefik.http.routers.sonarr.tls=true"
      - "traefik.http.routers.sonarr.tls.certresolver=myresolver"
      - "traefik.http.routers.sonarr.service=sonarr"
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
      # Radarr
      - "traefik.http.routers.radarr.rule=Host(`radarr.bspwr.com`)"
      - "traefik.http.routers.radarr.entrypoints=websecure"
      - "traefik.http.routers.radarr.tls=true"
      - "traefik.http.routers.radarr.tls.certresolver=myresolver"
      - "traefik.http.routers.radarr.service=radarr"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"
      # Bazarr
      - "traefik.http.routers.bazarr.rule=Host(`bazarr.bspwr.com`)"
      - "traefik.http.routers.bazarr.entrypoints=websecure"
      - "traefik.http.routers.bazarr.tls=true"
      - "traefik.http.routers.bazarr.tls.certresolver=myresolver"
      - "traefik.http.routers.bazarr.service=bazarr"
      - "traefik.http.services.bazarr.loadbalancer.server.port=6767"
      # Lidarr
      - "traefik.http.routers.lidarr.rule=Host(`lidarr.bspwr.com`)"
      - "traefik.http.routers.lidarr.entrypoints=websecure"
      - "traefik.http.routers.lidarr.tls=true"
      - "traefik.http.routers.lidarr.tls.certresolver=myresolver"
      - "traefik.http.routers.lidarr.service=lidarr"
      - "traefik.http.services.lidarr.loadbalancer.server.port=8686"
      # Readarr
      - "traefik.http.routers.readarr.rule=Host(`readarr.bspwr.com`)"
      - "traefik.http.routers.readarr.entrypoints=websecure"
      - "traefik.http.routers.readarr.tls=true"
      - "traefik.http.routers.readarr.tls.certresolver=myresolver"
      - "traefik.http.routers.readarr.service=readarr"
      - "traefik.http.services.readarr.loadbalancer.server.port=8787"
      # Prowlarr
      - "traefik.http.routers.prowlarr.rule=Host(`prowlarr.bspwr.com`)"
      - "traefik.http.routers.prowlarr.entrypoints=websecure"
      - "traefik.http.routers.prowlarr.tls=true"
      - "traefik.http.routers.prowlarr.tls.certresolver=myresolver"
      - "traefik.http.routers.prowlarr.service=prowlarr"
      - "traefik.http.services.prowlarr.loadbalancer.server.port=9696"
      # Jellyseerr
      - "traefik.http.routers.jellyseerr.rule=Host(`jellyseerr.bspwr.com`)"
      - "traefik.http.routers.jellyseerr.entrypoints=websecure"
      - "traefik.http.routers.jellyseerr.tls=true"
      - "traefik.http.routers.jellyseerr.tls.certresolver=myresolver"
      - "traefik.http.routers.jellyseerr.service=jellyseerr"
      - "traefik.http.services.jellyseerr.loadbalancer.server.port=5055"
      # Flaresolverr
      - "traefik.http.routers.flaresolverr.rule=Host(`flaresolverr.bspwr.com`)"
      - "traefik.http.routers.flaresolverr.entrypoints=websecure"
      - "traefik.http.routers.flaresolverr.tls=true"
      - "traefik.http.routers.flaresolverr.tls.certresolver=myresolver"
      - "traefik.http.routers.flaresolverr.service=flaresolverr"
      - "traefik.http.services.flaresolverr.loadbalancer.server.port=8191"

  # Torrent Client
  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    environment:
      - PUID=1420
      - PGID=1420
      - TZ=America/New_York
    volumes:
      - /services/arr/deluge:/config:Z
      - /ocean/downloads:/downloads:z
    depends_on:
      - wireguard-arr
    network_mode: service:wireguard-arr
    restart: unless-stopped
    healthcheck:
      test: curl --fail localhost:8112 && curl --fail https://am.i.mullvad.net/connected | grep "You are connected to Mullvad" || exit 1
      interval: 30s
      retries: 10
      start_period: 10s
      timeout: 2s

  # TV
  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1420
      - PGID=1420
      - TZ=America/New_York
    volumes:
      - /services/arr/sonarr:/config:Z
      - /ocean/media/shows:/shows:z
      - /ocean/downloads:/downloads:z
    depends_on:
      - wireguard-arr
    network_mode: service:wireguard-arr
    restart: unless-stopped
    healthcheck:
      test: curl --fail localhost:8989 || exit 1
      interval: 10s
      retries: 6
      start_period: 10s
      timeout: 2s

  # Movies
  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1420
      - PGID=1420
      - TZ=America/New_York
    volumes:
      - /services/arr/radarr:/config:Z
      - /ocean/media/movies:/movies:z
      - /ocean/downloads:/downloads:z
    depends_on:
      - wireguard-arr
    network_mode: service:wireguard-arr
    restart: unless-stopped
    healthcheck:
      test: curl --fail localhost:7878 || exit 1
      interval: 10s
      retries: 6
      start_period: 10s
      timeout: 2s

  # Subtitles
  bazarr:
    image: lscr.io/linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=1420
      - PGID=1420
      - TZ=America/New_York
    volumes:
      - /services/arr/bazarr:/config:Z
      - /ocean/media/movies:/movies:z
      - /ocean/downloads:/tv:z
    depends_on:
      - wireguard-arr
    network_mode: service:wireguard-arr
    restart: unless-stopped
    healthcheck:
      test: curl --fail localhost:6767 || exit 1
      interval: 10s
      retries: 6
      start_period: 10s
      timeout: 2s

  # Music
  lidarr:
    image: lscr.io/linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID=1420
      - PGID=1420
      - TZ=America/New_York
    volumes:
      - /services/arr/lidarr:/config:Z
      - /ocean/media/music:/music:z
      - /ocean/downloads:/downloads:z
    depends_on:
      - wireguard-arr
    network_mode: service:wireguard-arr
    restart: unless-stopped
    healthcheck:
      test: curl --fail localhost:8686 || exit 1
      interval: 10s
      retries: 6
      start_period: 10s
      timeout: 2s

  # Books
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=1420
      - PGID=1420
      - TZ=America/New_York
    volumes:
      - /services/arr/readarr:/config:Z
      - /ocean/media/books:/books:z
      - /ocean/downloads:/downloads:z
    depends_on:
      - wireguard-arr
    network_mode: service:wireguard-arr
    restart: unless-stopped
    healthcheck:
      test: curl --fail localhost:8787 || exit 1
      interval: 10s
      retries: 6
      start_period: 10s
      timeout: 2s

  # Indexer Manager
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=1420
      - PGID=1420
      - TZ=America/New_York
    volumes:
      - /services/arr/prowlarr:/config:Z
    depends_on:
      - wireguard-arr
    network_mode: service:wireguard-arr
    restart: unless-stopped
    healthcheck:
      test: curl --fail localhost:9696 || exit 1
      interval: 10s
      retries: 6
      start_period: 10s
      timeout: 2s

  # Media Request Manager for Jellyfin
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - TZ=America/New_York
    volumes:
      - /services/arr/jellyseerr:/app/config
    depends_on:
      - wireguard-arr
    network_mode: service:wireguard-arr
    restart: unless-stopped
    healthcheck:
      test: wget --no-verbose --tries=1 --spider localhost:5055 || exit 1
      interval: 10s
      retries: 6
      start_period: 10s
      timeout: 2s

  # Proxy server to bypass Cloudflare protection
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - TZ=America/New_York
    depends_on:
      - wireguard-arr
    network_mode: service:wireguard-arr
    restart: unless-stopped

networks:
  arr:
    name: arr
    external: true